include(FindPkgConfig)
find_package(PkgConfig)

if(PKG_CONFIG_FOUND)
  pkg_check_modules (LIBVLCPP libvlcpp)
  IF (LIBVLCPP_FOUND)
    pkg_check_modules (LIBVLC libvlc)
  endif()
endif()

IF (LIBVLC_FOUND)
   get_filename_component(LIBVLC_LIB_DIR "${LIBVLC_LIBRARY}" PATH)
   IF (NOT LIBVLC_FIND_QUIETLY)
      MESSAGE(STATUS "Found LibVLC include-dir path: ${LIBVLC_INCLUDE_DIRS}")
      MESSAGE(STATUS "Found LibVLCPP include-dir path: ${LIBVLCPP_INCLUDE_DIRS}")
      MESSAGE(STATUS "Found LibVLC library path:${LIBVLC_LIBRARY_DIRS}")
   ENDIF (NOT LIBVLC_FIND_QUIETLY)
ELSE (LIBVLC_FOUND)
   IF (LIBVLC_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find LibVLC")
   ENDIF (LIBVLC_FIND_REQUIRED)
ENDIF (LIBVLC_FOUND)
